# -- Library of NMEA fields
[talker_ids]
AB = "NMEA 4.0 Base AIS station"
AD = "NMEA 4.0 Dependent AIS Base Station"
AI = "Mobile AIS station"
AN = "NMEA 4.0 Aid to Navigation AIS station"
AR = "NMEA 4.0 AIS Receiving Station"
AS = "NMEA 4.0 Limited Base Station"
AT = "NMEA 4.0 AIS Transmitting Station"
AX = "NMEA 4.0 Repeater AIS station"
BS = "Base AIS station (deprecated in NMEA 4.0)"
SA = "NMEA 4.0 Physical Shore AIS Station"

[identifiers]
VDO = "Reports from your own ship"
VDM = "Reports from other ships"
# AAM = 'Waypoint Arrival Alarm'
# ALM = 'GPS Almanac Data'
# APA = 'Autopilot Sentence "A"'
# APB = 'Autopilot Sentence "B"'
# BOD = 'Bearing - Waypoint to Waypoint'
# BWC = 'Bearing & Distance to Waypoint - Great Circle'
# BWR = 'Bearing and Distance to Waypoint - Rhumb Line'
# BWW = 'Bearing - Waypoint to Waypoint'
# DBK = 'Depth Below Keel'
# DBS = 'Depth Below Surface'
# DBT = 'Depth below transducer'
# DCN = 'Decca Position'
# DPT = 'Depth of Water'
# DTM = 'Datum Reference'
# FSI = 'Frequency Set Information'
# GBS = 'GPS Satellite Fault Detection'
# GGA = 'Global Positioning System Fix Data'
# GLC = 'Geographic Position, Loran-C'
# GLL = 'Geographic Position - Latitude/Longitude'
# GNS = 'Fix data'
# GRS = 'GPS Range Residuals'
# GST = 'GPS Pseudorange Noise Statistics'
# GSA = 'GPS DOP and active satellites'
# GSV = 'Satellites in view'
# GTD = 'Geographic Location in Time Differences'
# GXA = 'TRANSIT Position - Latitude/Longitude'
# HDG = 'Heading - Deviation & Variation'
# HDM = 'Heading - Magnetic'
# HDT = 'Heading - True'
# HFB = 'Trawl Headrope to Footrope and Bottom'
# HSC = 'Heading Steering Command'
# HWBIAS = 'Unknown'
# ITS = 'Trawl Door Spread 2 Distance'
# LCD = 'Loran-C Signal Data'
# MDA = 'Meteorological Composite'
# MSK = 'Control for a Beacon Receiver'
# MSS = 'Beacon Receiver Status'
# MTW = 'Mean Temperature of Water'
# MWD = 'Wind Direction & Speed'
# MWV = 'Wind Speed and Angle'
# OLN = 'Omega Lane Numbers'
# OSD = 'Own Ship Data'
# R00 = 'Waypoints in active route'
# RLM = 'Return Link Message'
# RMA = 'Recommended Minimum Navigation Information'
# RMB = 'Recommended Minimum Navigation Information'
# RMC = 'Recommended Minimum Navigation Information'
# ROT = 'Rate Of Turn'
# RPM = 'Revolutions'
# RSA = 'Rudder Sensor Angle'
# RSD = 'RADAR System Data'
# RTE = 'Routes'
# SFI = 'Scanning Frequency Information'
# STN = 'Multiple Data ID'
# TDS = 'Trawl Door Spread Distance'
# TFI = 'Trawl Filling Indicator'
# TLB = 'Target Label'
# TLL = 'Target Latitude and Longitude'
# TPC = 'Trawl Position Cartesian Coordinates'
# TPR = 'Trawl Position Relative Vessel'
# TPT = 'Trawl Position True'
# TRF = 'TRANSIT Fix Data'
# TTM = 'Tracked Target Message'
# VBW = 'Dual Ground/Water Speed'
# VDR = 'Set and Drift'
# VHW = 'Water speed and heading'
# VLW = 'Distance Traveled through Water'
# VPW = 'Speed - Measured Parallel to Wind'
# VTG = 'Track made good and Ground speed'
# VWR = 'Relative Wind Speed and Angle'
# WCV = 'Waypoint Closure Velocity'
# WNC = 'Distance - Waypoint to Waypoint'
# WPL = 'Waypoint Location'
# XDR = 'Transducer Measurement'
# XTE = 'Cross-Track Error, Measured'
# XTR = 'Cross Track Error - Dead Reckoning'
# ZDA = 'Time & Date - UTC, day, month, year and local time zone'
# ZFO = 'UTC & Time from origin Waypoint'
# ZTG = 'UTC & Time to Destination Waypoint'

[radio_channels]
A = "161.975Mhz (87B)"
1 = "161.975Mhz (87B)"
B = "162.025Mhz (88B)"
2 = "162.025Mhz (88B)"
