# -- Library of NMEA fields
[talker_ids]
# List of NMEA 4.0 Talker Identifyer mnemonics as defined in:
#     NMEA 0183 Version 4, paragraph 6.1.4, table 6
AB = "Independent AIS Base Station"
AD = "Dependent AIS Base Station"
AG = "HEADING TRACK CONTROLLER (Autopilot): General"
AP = "HEADING TRACK CONTROLLER (Autopilot): Magnetic"
AI = "Mobile Class A or B AIS Station"
AN = "AIS Aids to Navigation Station"
AR = "AIS Receiving Station"
AS = "AIS Station (ITU_R M1371, Limited Base Station)"
AT = "AIS Transmitting Station"
AX = "AIS Simplex Repeater Station"
BI = "Bilge Systems"
CD = "COMMUNICATIONS: Digital Selective Calling (DSC)"
CR = "COMMUNICATIONS: Data Receiver"
CS = "COMMUNICATIONS: Satellite"
CT = "COMMUNICATIONS: Radio-Telephone (MF/HF)"
CV = "COMMUNICATIONS: Radio-Telephone (VHF)"
CX = "COMMUNICATIONS: Scanning Receiver"
DE = "DECCA Navigator"
DF = "Direction Finder"
DU = "Duplex Repeater Station"
EC = "Electronic Chart System (ECS)"
EI = "Electronic Chart Display & Information System (ECDIS)"
EP = "Emergency Position Indicating Beacon (EPIRB)"
ER = "Engine room Monitoring Systems"
FD = "Fire Door Controller/Monitoring Point"
FE = "Fire Extinguisher System"
FR = "Fire Detection Point"
FS = "Fire Sprinkler System"
GA = "Galileo Positioning System"
GL = "GLONASS Receiver"
GN = "Global Navigation Satellite System (GNSS)"
GP = "Global Positioning System (GPS)"
HC = "HEADING SENSORS: Compass, Magnetic"
HE = "HEADING SENSORS: Gyro, North Seeking"
HF = "HEADING SENSORS: Fluxgate"
HN = "HEADING SENSORS: Gyro, Non-North Seeking"
HD = "Hull Door Controller/Monitoring Panel"
HS = "Hull Stress Monitoring"
II = "Integrated Instrumentation"
IN = "Integrated Navigation"
LC = "Loran C"
P = "Proprietary Code"
RA = "Radar and/or Radar Plotting"
RC = "Propulsion Machinery Including Remote Control"
SA = "Physical Shore AIS Station"
SD = "Sounder, depth"
SG = "Steering Gear/Steering Engine"
SN = "Electronic Positioning System, other/general"
SS = "Sounder, scanning"
TI = "Turn Rate Indicator"
UP = "Microprocessor Controller"
U0 = "User configured talker identifier"
U1 = "User configured talker identifier"
U2 = "User configured talker identifier"
U3 = "User configured talker identifier"
U4 = "User configured talker identifier"
U5 = "User configured talker identifier"
U6 = "User configured talker identifier"
U7 = "User configured talker identifier"
U8 = "User configured talker identifier"
U9 = "User configured talker identifier"
VD = "VELOCITY SENSORS: Doppler, other/general"
VM = "VELOCITY SENSORS: Speed Log, Water, Magnetic"
VW = "VELOCITY SENSORS: Speed Log, Water Mechanical"
VR = "Voyage Data Recorder"
WD = "Watertight Door Controller/Monitoring Panel"
WI = "Weather Instruments"
WL = "Water Level Detection Systems"
YX = "Transducer"
ZA = "TIMEKEEPERS, TIME/DATE: Atomics Clock"
ZC = "TIMEKEEPERS, TIME/DATE: Chronometer"
ZQ = "TIMEKEEPERS, TIME/DATE: Quartz"
ZV = "TIMEKEEPERS, TIME/DATE: Radio Update"

[sentence_formatters]
# List of NMEA 4.0 Talker Identifyer mnemonics as defined in:
#     NMEA 0183 Version 4, Complete List of Approved Sentence Formatters - Alphabetical Order
AAM = "Waypoint Arrival Alarm"
ABK = "AIS Addressed and Binary Broadcast Acknowledgement"
ABM = "AIS Addressed Binary and Safety Related Message"
ACA = "AIS Regional Channel Assignment Message"
ACF = "General AtoN Station Configuration Command"
ACG = "Extended General AtoN Station Configuration Command"
ACK = "Acknowledge Alarm"
ACM = "AIS Base Station Addressed Channel Management Command"
ACS = "AIS Channel Management Information Source"
ADS = "Automatic Device Status"
AFB = "AtoN Forced Broadcast Command"
AGA = "AIS Base Station Broadcast of a Group Assignment Command"
AID = "AtoN IDentification Configuration Command"
AIR = "AIS Interrogation Request"
AKD = "Acknowledge Detail Alarm Condition"
ALA = "Set Detail Alarm Condition"
ALM = "GPS Almanac Data"
ALR = "Set Alarm State"
APB = "Heading/Track Controller (Autopilot) Sentence 'B'"
ASN = "AIS Base Station Broadcast of Assignment Command"
BBM = "AIS Broadcast Binary Message"
BCG = "Base Station Configuration, General Command"
BCL = "Base Station Configuration, Location Command"
BEC = "Bearing & Distance to Waypoint = Dead Reckoning"
BOD = "Bearing - Origin to Destination"
BWC = "Bearing & Distance to Waypoint = Great Circle"
BWR = "Bearing & Distance to Waypoint = Rhumb Line"
BWW = "Bearing = Waypoint to Waypoint"
CBR = "Configure Broadcast Rates for AIS AtoN Station Message Command"
CEK = "Configure Encryption Key Command"
COP = "Configure the Operational Period, Command"
CPC = "Configure Parameter-code for UNIX Time Parameter (c)"
CPD = "Configure Parameter-code for Destination-identification Parameter (d"
CPG = "Configure Parameter-code for the Sentence-Grouping Parameter (g)"
CPN = "Configure Parameter-code for the Line-count Parameter (n)"
CPR = "Configure Parameter-code for Relative (epoch / event) Time Parameter (r)"
CPS = "Configure Parameter-code for the Source-identification Parameter(s)"
CPT = "Configure Parameter-code for a Text-string Parameter (t)"
CUR = "Water Current Layer"
DBT = "Depth Below Transducer"
DCN = "DECCA position"
DCR = "Device Capability Report"
DDC = "Display Dimming Control"
DLM = "Data Link Management Slot Allocations for Base Station Command"
DOR = "Door Status Detection"
DPT = "Depth"
DSC = "Digital Selective Calling Information"
DSE = "Expanded Digital Selective Calling"
DSI = "DSC Transponder Initialize"
DSR = "DSC Transponder Response"
DTM = "Datum Reference"
ECB = "Configure Broadcast Schedules for Base Station Messages, Command"
ETL = "Engine Telegraph Operation Status"
EVE = "General Event Message"
FIR = "Fire Detection"
FSI = "Frequency Set Status or Command"
FSR = "Frame Summary of AIS Reception"
GBS = "GNSS Satellite Fault Detection"
GEN = "Generic Status Information"
GGA = "Global Positioning System Fix Data"
GLC = "Geographic Position = Loran-C"
GLL = "Geographic Position = Latitude/Longitude"
GMP = "GNSS Map Projection Fix Data"
GNS = "GNSS Fix Data"
GRS = "GNSS Range Residuals"
GSA = "GNSS DOP and Active Satellites"
GST = "GNSS Pseudorange Error Statistics"
GSV = "GNSS Satellites In View"
HDG = "Heading, Deviation & Variation"
HDT = "Heading, True"
HMR = "Heading Monitor Receive"
HMS = "Heading Monitor Set"
HSC = "Heading Steering Command"
HSS = "Hull Stress Surveillance Systems"
HTC = "Heading/Track Control Command"
HTD = "Heading/Track Control Data"
LCD = "Loran-C Signal Data"
LR1 = "AIS Long-range Reply Sentence 1"
LR2 = "AIS Long-range Reply Sentence 2"
LR3 = "AIS Long-range Reply Sentence 3"
LRF = "AIS Long-Range Function"
LRI = "AIS Long-Range Interrogation"
MEB = "Message Input for Broadcast, Command"
MLA = "GLONASS Almanac Data"
MSK = "MSK Receiver Interface Command"
MSS = "MSK Receiver Signal"
MTW = "Water Temperature"
MWD = "Wind Direction & Speed"
MWV = "Wind Speed & Angle"
NAK = "Negative Acknowledgement"
NRM = "NAVTEX Receiver Mask Command"
NRX = "NAVTEX Received Message"
OSD = "Own Ship Data"
PRC = "Propulsion Remote Control Status"
RMA = "Recommended Minimum Specific Loran-C Data"
RMB = "Recommended Minimum Navigation Information"
RMC = "Recommended Minimum Specific GNSS Data"
ROR = "Rudder Order Status"
ROT = "Rate Of Turn"
RPM = "Revolutions"
RSA = "Rudder Sensor Angle"
RSD = "Radar System Data"
RST = "Equipment Reset Command"
RTE = "Routes RTE = Routes"
SFI = "Scanning Frequency Information Status and Command"
SID = "Set an Equipment’s IDentification and Command"
SPO = "Select AIS Device’s Processing and Output, Command"
SSD = "AIS Ship Static Data"
STN = "Multiple Data ID"
TBR = "TAG Block Report Request"
TBS = "TAG Block listener Source-identification Configuration Command"
TFR = "Transmit Feed-Back Report"
THS = "True Heading and Status"
TLB = "Target Label"
TLL = "Target Latitude and Longitude"
TPC = "Transmit Slot Prohibit, Command"
TRC = "Thruster Control Data"
TRD = "Thruster Response Data"
TSA = "Transmit Slot Assignment"
TSP = "Temporary Transmit Slot Prohibit"
TSR = "Transmit Slot Prohibit Status Report"
TTD = "Tracked Target Data"
TTM = "Tracked Target Message"
TUT = "Transmission of Multi-language Text"
TXT = "Text Transmission"
UID = "User Identification Code Transmission"
VBW = "Dual Ground/Water Speed"
VDM = "AIS VHF Data-link Message"
VDO = "AIS VHF Data-Link Own-Vessel Report"
VDR = "Set & Drift"
VER = "Version"
VHW = "Water Speed and Heading"
VLW = "Dual Ground/Water Distance"
VPW = "Speed = Measured Parallel to Wind"
VSD = "AIS Voyage Static Data"
VSI = "VDL Signal Information"
VTG = "Course Over Ground & Ground Speed"
WAT = "Water Level Detection"
WCV = "Waypoint Closure Velocity"
WNC = "Distance = Waypoint to Waypoint"
WPL = "Waypoint Location"
XDR = "Transducer Measurements"
XTE = "Cross-Track Error, Measured"
XTR = "Cross-Track Error = Dead Reckoning"
ZDA = "Time & Date"
ZDL = "Time & Distance to Variable Point"
ZFO = "UTC & Time from Origin Waypoint"
ZTG = "UTC & Time to Destination Waypoint"


[radio_channels]
A = "161.975Mhz (87B)"
1 = "161.975Mhz (87B)"
B = "162.025Mhz (88B)"
2 = "162.025Mhz (88B)"
